# Generated by Django 4.2.7 on 2024-01-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=3)),
                ('roll', models.IntegerField()),
                ('batch', models.CharField(max_length=7)),
            ],
        ),
    ]
